/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8FPsFEcwfPwJTeYKjXtkVp
// Component: bUzvmv2Yjdda

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 8FPsFEcwfPwJTeYKjXtkVp/projectcss
import sty from "./PlasmicRatings.module.css"; // plasmic-import: bUzvmv2Yjdda/css

import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: vC-AT7Sgsmpi/icon

createPlasmicElementProxy;

export type PlasmicRatings__VariantMembers = {
  stars: "zero" | "one" | "two" | "three" | "four" | "five";
};
export type PlasmicRatings__VariantsArgs = {
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
};
type VariantPropType = keyof PlasmicRatings__VariantsArgs;
export const PlasmicRatings__VariantProps = new Array<VariantPropType>("stars");

export type PlasmicRatings__ArgsType = { numReviews?: React.ReactNode };
type ArgPropType = keyof PlasmicRatings__ArgsType;
export const PlasmicRatings__ArgProps = new Array<ArgPropType>("numReviews");

export type PlasmicRatings__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
};

export interface DefaultRatingsProps {
  numReviews?: React.ReactNode;
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRatings__RenderFunc(props: {
  variants: PlasmicRatings__VariantsArgs;
  args: PlasmicRatings__ArgsType;
  overrides: PlasmicRatings__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "stars",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.stars
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootstars_five]: hasVariant($state, "stars", "five"),
          [sty.rootstars_four]: hasVariant($state, "stars", "four"),
          [sty.rootstars_one]: hasVariant($state, "stars", "one"),
          [sty.rootstars_three]: hasVariant($state, "stars", "three"),
          [sty.rootstars_two]: hasVariant($state, "stars", "two"),
          [sty.rootstars_zero]: hasVariant($state, "stars", "zero")
        }
      )}
    >
      <Stack__
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <StarIcon
          className={classNames(projectcss.all, sty.svg__m3RBf, {
            [sty.svgstars_five__m3RBfbs8Pb]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_zero__m3RBfUtpSq]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__wRtlE, {
            [sty.svgstars_five__wRtlEbs8Pb]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four__wRtlEFtOmx]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_one__wRtlEIkSjb]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__wRtlEMajRo]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__wRtlElcsDf]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__wRtlEUtpSq]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__tAlr, {
            [sty.svgstars_five__tAlrBs8Pb]: hasVariant($state, "stars", "five"),
            [sty.svgstars_four__tAlrFtOmx]: hasVariant($state, "stars", "four"),
            [sty.svgstars_one__tAlrIkSjb]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__tAlrMajRo]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__tAlrLcsDf]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__tAlrUtpSq]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__kiFy, {
            [sty.svgstars_five__kiFyBs8Pb]: hasVariant($state, "stars", "five"),
            [sty.svgstars_four__kiFyFtOmx]: hasVariant($state, "stars", "four"),
            [sty.svgstars_one__kiFyIkSjb]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__kiFyMajRo]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__kiFyLcsDf]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__kiFyUtpSq]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__mhaJi, {
            [sty.svgstars_five__mhaJiBs8Pb]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four__mhaJiFtOmx]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_one__mhaJiIkSjb]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__mhaJiMajRo]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__mhaJiLcsDf]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__mhaJiUtpSq]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__ydZmv, {
            [sty.svgstars_five__ydZmvbs8Pb]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four__ydZmvFtOmx]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_one__ydZmvIkSjb]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__ydZmvMajRo]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__ydZmvlcsDf]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__ydZmvUtpSq]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__pbqC, {
            [sty.svgstars_five__pbqCbs8Pb]: hasVariant($state, "stars", "five"),
            [sty.svgstars_four__pbqCFtOmx]: hasVariant($state, "stars", "four"),
            [sty.svgstars_three__pbqCMajRo]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__pbqClcsDf]: hasVariant($state, "stars", "two")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__cmH5, {
            [sty.svgstars_five__cmH5Bs8Pb]: hasVariant($state, "stars", "five"),
            [sty.svgstars_four__cmH5FtOmx]: hasVariant($state, "stars", "four"),
            [sty.svgstars_three__cmH5MajRo]: hasVariant(
              $state,
              "stars",
              "three"
            )
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__kQdNg, {
            [sty.svgstars_five__kQdNgbs8Pb]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four__kQdNgFtOmx]: hasVariant($state, "stars", "four")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__x0WJm, {
            [sty.svgstars_five__x0WJmbs8Pb]: hasVariant($state, "stars", "five")
          })}
          role={"img"}
        />
      </Stack__>
      {renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotTargetNumReviews)
      })}
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRatings__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRatings__VariantsArgs;
    args?: PlasmicRatings__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRatings__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRatings__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicRatings__ArgProps,
          internalVariantPropNames: PlasmicRatings__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
