/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8FPsFEcwfPwJTeYKjXtkVp
// Component: mW1bGmlsIUCo

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header2 from "../../Header2"; // plasmic-import: hmaXZuvwR90s/component
import ProductCard from "../../ProductCard"; // plasmic-import: a9sywAIFgNty/component
import Ratings from "../../Ratings"; // plasmic-import: bUzvmv2Yjdda/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: mO2Fghscjgep/component
import BlogPost from "../../BlogPost"; // plasmic-import: iOUatfe-aEY2/component
import Footer from "../../Footer"; // plasmic-import: DhmVQn3kFNyW/component
import ProductRow from "../../ProductRow"; // plasmic-import: ETheLnHfuPnE/component

import { useScreenVariants as useScreenVariantswvxiCa7KExGf } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: WvxiCA7KExGF/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 8FPsFEcwfPwJTeYKjXtkVp/projectcss
import sty from "./PlasmicStore.module.css"; // plasmic-import: mW1bGmlsIUCo/css

import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: UUpnGxTt_l_h/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: vAh8ks_0WWjZ/icon

createPlasmicElementProxy;

export type PlasmicStore__VariantMembers = {};
export type PlasmicStore__VariantsArgs = {};
type VariantPropType = keyof PlasmicStore__VariantsArgs;
export const PlasmicStore__VariantProps = new Array<VariantPropType>();

export type PlasmicStore__ArgsType = {};
type ArgPropType = keyof PlasmicStore__ArgsType;
export const PlasmicStore__ArgProps = new Array<ArgPropType>();

export type PlasmicStore__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<"div">;
  header2?: Flex__<typeof Header2>;
  featureItem?: Flex__<typeof FeatureItem>;
  allProduct?: Flex__<"div">;
  bigPlants?: Flex__<"div">;
  cactuses?: Flex__<"div">;
  bestSellers?: Flex__<"div">;
  productRow?: Flex__<typeof ProductRow>;
};

export interface DefaultStoreProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicStore__RenderFunc(props: {
  variants: PlasmicStore__VariantsArgs;
  args: PlasmicStore__ArgsType;
  overrides: PlasmicStore__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswvxiCa7KExGf()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__pyefD)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__hBsr6)}>
                <Header2
                  data-plasmic-name={"header2"}
                  data-plasmic-override={overrides.header2}
                  className={classNames("__wab_instance", sty.header2)}
                />
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox___1ZYl)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__u3Pg4
                )}
              >
                {"Top Collections"}
              </h2>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__nC7)}
            >
              <div className={classNames(projectcss.all, sty.column__vLlA5)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ilGdJ
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__xEjFq)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/galinaNMiziNqvJx5MUnsplashJpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1278,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$65.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings___7Zpy6
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__psqXr)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ixaHt
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__hb1R7)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/igorSonFvPxCqgtwcUnsplashJpg.jpg",
                        fullWidth: 640,
                        fullHeight: 481,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$80.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings___3DEgF
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__zw5B1)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__bmpNo
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__fgxH0)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/scottWebbORwRlTgBrPoUnsplashJpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1280,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$40.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__e7PZe
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__cvmeW)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__riZE
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__v9A5K)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/freddieMarriageUcfKyTanLuUnsplashJpg.jpg",
                        fullWidth: 640,
                        fullHeight: 427,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__uqxi
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
            </Stack__>
            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(projectcss.all, sty.freeBox___7ApO5)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aiMqm
                )}
              >
                {"Featured Products"}
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___1ZNob)}
            >
              <div className={classNames(projectcss.all, sty.column__tzgVf)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__zgLO
                  )}
                  price={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__k6Ogo
                      )}
                    >
                      {"$160.00"}
                    </div>
                  }
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__ebmJr
                      )}
                      numReviews={"(12 Review)"}
                      stars={"two"}
                    />
                  }
                  title={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__r185Q
                      )}
                    >
                      {"Designed Sofa"}
                    </div>
                  }
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___5O3Nw)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__lfYua
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__mJ8H)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/f2.jpg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$200.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__cOz6I
                      )}
                      stars={"four"}
                    />
                  }
                  title={"Dining Table"}
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__mud7V)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__nIjsw
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__bZiXj)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/f3.jpg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__k3BgF
                      )}
                      numReviews={"(23 Review)"}
                      stars={"five"}
                    />
                  }
                  title={"Chair and Table"}
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__dwNmQ)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__dnGpD
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__cz5JC)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/f4.jpg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$299.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__a9LPs
                      )}
                      numReviews={"(35 Review)"}
                    />
                  }
                  title={"Modern Arm Chair"}
                  withReviews={true}
                />
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__bfmYl)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5DeUs
                )}
              >
                {"Latest Blog"}
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__peLxx)}
            >
              <div className={classNames(projectcss.all, sty.column__im2Np)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__ccU3J)}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ttvBb)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/b1.jpg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__ro0L6)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__wJpYg)}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__g3QkS)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/b2.jpg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__aRp3W)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__jHSw)}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__zhqGt)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/b3.jpg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__patRm)}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___6Reu)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"90px"}
                src={{
                  src: "/plasmic/planty/images/adidas.png",
                  fullWidth: 90,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__qrInR)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"91px"}
                src={{
                  src: "/plasmic/planty/images/hm.png",
                  fullWidth: 91,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__wrX1J)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"98px"}
                src={{
                  src: "/plasmic/planty/images/kappa.png",
                  fullWidth: 98,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__gv1X)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"124px"}
                src={{
                  src: "/plasmic/planty/images/lacoste.png",
                  fullWidth: 124,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__vf5Vn)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"125px"}
                src={{
                  src: "/plasmic/planty/images/levis.png",
                  fullWidth: 125,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />
            </Stack__>
            <Footer
              className={classNames("__wab_instance", sty.footer__tHgV0)}
            />
          </div>
          <div
            data-plasmic-name={"allProduct"}
            data-plasmic-override={overrides.allProduct}
            className={classNames(projectcss.all, sty.allProduct)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__yNYs)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__t0Bqu
                )}
              >
                {"All Products"}
              </h2>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__pk412)}
            >
              <div className={classNames(projectcss.all, sty.column__aMdm)}>
                <div className={classNames(projectcss.all, sty.freeBox__nC85)}>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__yQd1D)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__mmB6
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Summer plants"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__qdpHt
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Plants from Europe"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__yuEhW
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Cactuses"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__eCnXf
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Big plants"}
                    </PlasmicLink__>
                  </Stack__>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__lbw5T)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__bKoE6)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__rDpai)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__j4QVi)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/planty/images/plant6Jpg.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__pm84W)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__pkRhX)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__h7T0)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__tweY
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {"Donec finibus"}
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gjWbJ
                        )}
                      >
                        {"bigplants"}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__uEhC
                        )}
                      >
                        {"$100.00"}
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__jyUk)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__wUPf)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/planty/images/plant1Jpg.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__rSwie)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__hbntp)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__w21Gi)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__lsOlq
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {"Nulla suscipit"}
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mcv5F
                        )}
                      >
                        {"bigplants "}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5___6TDd0
                        )}
                      >
                        {"$49.40 "}
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__kd8F5)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ol5Z1)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/planty/images/plant5Jpg.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__an11V)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__jn5S1)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kkAly)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__hpUiL
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {"Vestibulum eget"}
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zk3W7
                        )}
                      >
                        {"bigplants "}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__i82Xs
                        )}
                      >
                        {"$220.40 "}
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__r0MTm)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___47Gwv)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/planty/images/plant7Jpg.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__jkfWa)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__yfPy)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___8Xnjo
                      )}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__hFMZ
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {"Sed consectetur"}
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9J2TO
                        )}
                      >
                        {"bigplants "}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5___3Lsu3
                        )}
                      >
                        {"$18.40 "}
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__k4Nhf)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__fWrHe)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/planty/images/plant6Jpg.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__qoYPg)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__nqMuA)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__f0Og2)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___5TAsl
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {"Donec finibus"}
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zfoZe
                        )}
                      >
                        {"bigplants"}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5___1N9Rt
                        )}
                      >
                        {"$100.00"}
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__dfQe6)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__omw22)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/planty/images/plant2Webp.webp",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__jm0Ew)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__shsXc)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qqJeJ)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__yBMzP
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {"Integer porta"}
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___7SbyN
                        )}
                      >
                        {"Cactuses"}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__c02O
                        )}
                      >
                        {"$49.40 "}
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__xctpz)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___5Y0N1)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/planty/images/plant41Jpg.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__xyQnF)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__smZcK)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__slQuS)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__yTkt7
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {"Cras molestie"}
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__arZuk
                        )}
                      >
                        {"cactuses "}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5___8Yyw2
                        )}
                      >
                        {"$24.99"}
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__v3375)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__jp20R)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/planty/images/plant31Jpg.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox___3WZn)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__i7Heu)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__vtfAy)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__dueUt
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {"Curabitur eu tempor"}
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zfarF
                        )}
                      >
                        {"Cactuses"}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__rrAoF
                        )}
                      >
                        {"$49.40 "}
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__zeRg)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__njc3E)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/planty/images/plant9Webp.webp",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__v1SkK)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg___433Fl)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ap9W)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__lyziP
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        {"Fusce sagittis"}
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qsj0
                        )}
                      >
                        {"Cactuses"}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5___2PZal
                        )}
                      >
                        {"$49.40 "}
                      </h5>
                    </div>
                  </Stack__>
                </Stack__>
              </div>
            </Stack__>
          </div>
          <Stack__
            as={"div"}
            data-plasmic-name={"bigPlants"}
            data-plasmic-override={overrides.bigPlants}
            hasGap={true}
            className={classNames(projectcss.all, sty.bigPlants)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__qFgm1)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__hxlNo
                )}
              >
                {"Big plants"}
              </h2>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__uqvfo)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__y5DI)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___612TX)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant6Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__sGghp)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg___2JKuf)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__kzsAs)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__iKeG0
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Donec finibus"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pH1En
                    )}
                  >
                    {"bigplants"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__vsqnC
                    )}
                  >
                    {"$100.00"}
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__xuUsk)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__ev4Vp)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant1Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___3Jowo)}
                >
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__vRrl6)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__aGpbr)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__cUuXr
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Nulla suscipit"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pp8V8
                    )}
                  >
                    {"bigplants "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___75SXl
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__qV0K)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__vx4Sz)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant7Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__b2Ysw)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__cuI4X)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__drGrr)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__lvBlv
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Sed consectetur"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4G560
                    )}
                  >
                    {"bigplants "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___6W4Fe
                    )}
                  >
                    {"$18.40 "}
                  </h5>
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___3A4Rr)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant5Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___16PtT)}
                >
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__je3Lw)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__qJyd2)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__xbKkb
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Vestibulum eget"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wXaNz
                    )}
                  >
                    {"bigplants "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___8EMzj
                    )}
                  >
                    {"$220.40 "}
                  </h5>
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"cactuses"}
            data-plasmic-override={overrides.cactuses}
            hasGap={true}
            className={classNames(projectcss.all, sty.cactuses)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___4E7Xj)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__z3Gn6
                )}
              >
                {"Cactuses"}
              </h2>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__kzEqQ)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__sCuEm)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__n5NE6)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant41Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__tjaNp)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__fddru)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__dIgbu)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__m5Iiv
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Cras molestie"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__inQtZ
                    )}
                  >
                    {"cactuses "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___3DrT
                    )}
                  >
                    {"$24.99"}
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__nHff5)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___0BpyT)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant31Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__zf2Ou)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__f6JF)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__lunKk)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__zx98D
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Curabitur eu tempor"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yA3Rr
                    )}
                  >
                    {"Cactuses"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__fDfJv
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__q7GeB)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__raxU7)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant9Webp.webp",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__aqiku)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__zipF2)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__zhgxR)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__delPe
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Fusce sagittis"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6Mny1
                    )}
                  >
                    {"Fusce sagittis"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__tbOgL
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__mYfEu)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__bs2Ps)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant2Webp.webp",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__hLvZp)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__rqX9E)}
                    role={"img"}
                  />
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___5J98F)}
                >
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__sGsY
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Integer porta"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8MmGd
                    )}
                  >
                    {"Cactuses"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___26Ba2
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"bestSellers"}
            data-plasmic-override={overrides.bestSellers}
            hasGap={true}
            className={classNames(projectcss.all, sty.bestSellers)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__hYqwa)}
            >
              <Icon2Icon
                className={classNames(projectcss.all, sty.svg__tyRvO)}
                role={"img"}
              />

              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__wZlaj
                )}
              >
                {"Best sellers"}
              </h2>
            </Stack__>
            <ProductRow
              data-plasmic-name={"productRow"}
              data-plasmic-override={overrides.productRow}
              className={classNames("__wab_instance", sty.productRow)}
            />
          </Stack__>
          <Footer className={classNames("__wab_instance", sty.footer__n1P9)} />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "header2",
    "featureItem",
    "allProduct",
    "bigPlants",
    "cactuses",
    "bestSellers",
    "productRow"
  ],
  header: ["header", "header2", "featureItem"],
  header2: ["header2"],
  featureItem: ["featureItem"],
  allProduct: ["allProduct"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"],
  bestSellers: ["bestSellers", "productRow"],
  productRow: ["productRow"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: "div";
  header2: typeof Header2;
  featureItem: typeof FeatureItem;
  allProduct: "div";
  bigPlants: "div";
  cactuses: "div";
  bestSellers: "div";
  productRow: typeof ProductRow;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStore__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStore__VariantsArgs;
    args?: PlasmicStore__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicStore__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicStore__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStore__ArgProps,
          internalVariantPropNames: PlasmicStore__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStore__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStore";
  } else {
    func.displayName = `PlasmicStore.${nodeName}`;
  }
  return func;
}

export const PlasmicStore = Object.assign(
  // Top-level PlasmicStore renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    header2: makeNodeComponent("header2"),
    featureItem: makeNodeComponent("featureItem"),
    allProduct: makeNodeComponent("allProduct"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    bestSellers: makeNodeComponent("bestSellers"),
    productRow: makeNodeComponent("productRow"),

    // Metadata about props expected for PlasmicStore
    internalVariantProps: PlasmicStore__VariantProps,
    internalArgProps: PlasmicStore__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicStore;
/* prettier-ignore-end */
