/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8FPsFEcwfPwJTeYKjXtkVp
// Component: INprH8rX9W3H

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header2 from "../../Header2"; // plasmic-import: hmaXZuvwR90s/component
import ProductCard from "../../ProductCard"; // plasmic-import: a9sywAIFgNty/component
import Ratings from "../../Ratings"; // plasmic-import: bUzvmv2Yjdda/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: mO2Fghscjgep/component
import BlogPost from "../../BlogPost"; // plasmic-import: iOUatfe-aEY2/component
import Footer from "../../Footer"; // plasmic-import: DhmVQn3kFNyW/component

import { useScreenVariants as useScreenVariantswvxiCa7KExGf } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: WvxiCA7KExGF/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 8FPsFEcwfPwJTeYKjXtkVp/projectcss
import sty from "./PlasmicAboutUs.module.css"; // plasmic-import: INprH8rX9W3H/css

import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: UUpnGxTt_l_h/icon

createPlasmicElementProxy;

export type PlasmicAboutUs__VariantMembers = {};
export type PlasmicAboutUs__VariantsArgs = {};
type VariantPropType = keyof PlasmicAboutUs__VariantsArgs;
export const PlasmicAboutUs__VariantProps = new Array<VariantPropType>();

export type PlasmicAboutUs__ArgsType = {};
type ArgPropType = keyof PlasmicAboutUs__ArgsType;
export const PlasmicAboutUs__ArgProps = new Array<ArgPropType>();

export type PlasmicAboutUs__OverridesType = {
  root?: Flex__<"div">;
  foreground2?: Flex__<"div">;
  h1?: Flex__<"h1">;
  header?: Flex__<"div">;
  featureItem?: Flex__<typeof FeatureItem>;
  bigPlants?: Flex__<"div">;
  cactuses?: Flex__<"div">;
  weLove?: Flex__<"div">;
  weThink?: Flex__<"div">;
};

export interface DefaultAboutUsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAboutUs__RenderFunc(props: {
  variants: PlasmicAboutUs__VariantsArgs;
  args: PlasmicAboutUs__ArgsType;
  overrides: PlasmicAboutUs__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswvxiCa7KExGf()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox___7RiJt)}>
            <Header2
              className={classNames("__wab_instance", sty.header2__zicrq)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__h1Rq9)}>
              <Stack__
                as={"div"}
                data-plasmic-name={"foreground2"}
                data-plasmic-override={overrides.foreground2}
                hasGap={true}
                className={classNames(projectcss.all, sty.foreground2)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___5ToRw)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"We are Planty"}
                  </h1>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__lmt5B)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lmAMi
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobile")
                        ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                        : "Well, not really. We\u2019re Snipcart \u2014a bunch of geeks from Qu\u00e9bec City. Planty is a theme we built for Stackbit , a killer JAMstack site-builder. To enable e-commerce on Planty, you\u2019ll need to sign up for Snipcart. Testing is forever free, no credit card required."}
                    </div>
                  </div>
                </Stack__>
              </Stack__>
            </div>
          </div>
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__qyH6L)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__vQwnh)}>
                <Header2
                  className={classNames("__wab_instance", sty.header2___0RLwF)}
                />
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__i1Jbh)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__z6Qml
                )}
              >
                {"Top Collections"}
              </h2>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__zhjsm)}
            >
              <div className={classNames(projectcss.all, sty.column__rFUeR)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___39ZhG
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__o9Fxu)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/galinaNMiziNqvJx5MUnsplashJpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1278,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$65.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__qLmJe
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__lFr8L)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__m7Aq2
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__aLw2H)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/igorSonFvPxCqgtwcUnsplashJpg.jpg",
                        fullWidth: 640,
                        fullHeight: 481,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$80.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__wqaQf
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__cJOiN)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ihUA
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__rFdtt)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/scottWebbORwRlTgBrPoUnsplashJpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1280,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$40.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings___8BMp8
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__mvwaz)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__jYva3
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ljsr8)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/freddieMarriageUcfKyTanLuUnsplashJpg.jpg",
                        fullWidth: 640,
                        fullHeight: 427,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__qYs1F
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
            </Stack__>
            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__t0QH)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qzDh4
                )}
              >
                {"Featured Products"}
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__k2KyO)}
            >
              <div className={classNames(projectcss.all, sty.column__i19G6)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__msbg5
                  )}
                  price={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bgIi5
                      )}
                    >
                      {"$160.00"}
                    </div>
                  }
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__aWqy5
                      )}
                      numReviews={"(12 Review)"}
                      stars={"two"}
                    />
                  }
                  title={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___16B0
                      )}
                    >
                      {"Designed Sofa"}
                    </div>
                  }
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__u7Iau)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__wj8Fz
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ekQja)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/f2.jpg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$200.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__z88Y
                      )}
                      stars={"four"}
                    />
                  }
                  title={"Dining Table"}
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__wehL)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__beTuR
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__pU38V)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/f3.jpg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__aWs0R
                      )}
                      numReviews={"(23 Review)"}
                      stars={"five"}
                    />
                  }
                  title={"Chair and Table"}
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__xqRNr)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__wOFlH
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__jX2Ok)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/f4.jpg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$299.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__iDZgc
                      )}
                      numReviews={"(35 Review)"}
                    />
                  }
                  title={"Modern Arm Chair"}
                  withReviews={true}
                />
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox___4I8Z4)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dktT9
                )}
              >
                {"Latest Blog"}
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__xZjCn)}
            >
              <div className={classNames(projectcss.all, sty.column__zLmJ4)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost___7Z8N)}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__rmV2L)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/b1.jpg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__gZx6Z)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__upddv)}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__itd8)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/b2.jpg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__fJ8At)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__xDvKm)}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__oEg81)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/planty/images/b3.jpg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___5SrKs)}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__oUfeN)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"90px"}
                src={{
                  src: "/plasmic/planty/images/adidas.png",
                  fullWidth: 90,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__yIi8R)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"91px"}
                src={{
                  src: "/plasmic/planty/images/hm.png",
                  fullWidth: 91,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__m5Pom)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"98px"}
                src={{
                  src: "/plasmic/planty/images/kappa.png",
                  fullWidth: 98,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__vM2As)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"124px"}
                src={{
                  src: "/plasmic/planty/images/lacoste.png",
                  fullWidth: 124,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__oDtmz)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"125px"}
                src={{
                  src: "/plasmic/planty/images/levis.png",
                  fullWidth: 125,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />
            </Stack__>
            <Footer
              className={classNames("__wab_instance", sty.footer__kpsc8)}
            />
          </div>
          <Stack__
            as={"div"}
            data-plasmic-name={"bigPlants"}
            data-plasmic-override={overrides.bigPlants}
            hasGap={true}
            className={classNames(projectcss.all, sty.bigPlants)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__g4Ujk)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__pIhYz
                )}
              >
                {"Big plants"}
              </h2>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__r9WpU)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__bBnDa)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__xm8Zg)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant6Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__lpsiZ)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg___3DwVu)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__lJJgJ)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__zGw0O
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Donec finibus"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zyVs4
                    )}
                  >
                    {"bigplants"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__nokU2
                    )}
                  >
                    {"$100.00"}
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___8Iret)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__fWy5W)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant1Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__jzcoh)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__jaGhY)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__uTdOk)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___6AXwA
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Nulla suscipit"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gDXtc
                    )}
                  >
                    {"bigplants "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___6Uoex
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___70TRk)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__y7Wt3)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant7Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__uoGwm)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__qgpNz)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__ki6Tl)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__eopyb
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Sed consectetur"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mAt06
                    )}
                  >
                    {"bigplants "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__uMfo2
                    )}
                  >
                    {"$18.40 "}
                  </h5>
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___4MdJn)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant5Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__b4P1F)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__k0VBa)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__pZFn)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__faPhT
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Vestibulum eget"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__owo6Q
                    )}
                  >
                    {"bigplants "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__xgZzZ
                    )}
                  >
                    {"$220.40 "}
                  </h5>
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"cactuses"}
            data-plasmic-override={overrides.cactuses}
            hasGap={true}
            className={classNames(projectcss.all, sty.cactuses)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__a2Bl4)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__fgOj
                )}
              >
                {"Cactuses"}
              </h2>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__ooO0)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___5BkCm)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___70GR)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant41Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__lhlSq)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__iyg3A)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__yaKj1)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__rfCxn
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Cras molestie"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___82DCo
                    )}
                  >
                    {"cactuses "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___26G6L
                    )}
                  >
                    {"$24.99"}
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__hiyI)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__vKoDe)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant31Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__mf9Xw)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__kEmS1)}
                    role={"img"}
                  />
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___8IhlN)}
                >
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__wmfn
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Curabitur eu tempor"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8TxVo
                    )}
                  >
                    {"Cactuses"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__zehv9
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__zSAid)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__d7DQz)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant9Webp.webp",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__xVjf1)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__eZmJq)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__fYoyZ)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__cy3Jo
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Fusce sagittis"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cun6C
                    )}
                  >
                    {"Fusce sagittis"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__qkZjz
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__bzQqT)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__oU9EX)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/planty/images/plant2Webp.webp",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__ecPp2)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__pEnbo)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__dVcGs)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__m3M2H
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Integer porta"}
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dt8O3
                    )}
                  >
                    {"Cactuses"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__oH5Sf
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <div
            data-plasmic-name={"weLove"}
            data-plasmic-override={overrides.weLove}
            className={classNames(projectcss.all, sty.weLove)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___7Hrmb)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__oCenR)}
              >
                <div className={classNames(projectcss.all, sty.column___8Aq8Z)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__w4OXm)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "400px"
                        : "500px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"500px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/planty/images/nanTalkWebp.webp",
                      fullWidth: 1000,
                      fullHeight: 1498,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__nXunG)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__xPfhC
                    )}
                  >
                    {"Testimonials"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___87Ce
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                      : "Now THAT is true, but we love web development even more. We talk about it on our blog, like, a lot.  We often craft live demos and open source these bad boys on GitHub. Matter of fact, this Planty theme is open source too! If you spot any bugs, open an issue, and we\u2019ll fire our junior dev. Just kidding Michael, you\u2019re good."}
                  </div>
                </Stack__>
              </Stack__>
            </div>
          </div>
          <div
            data-plasmic-name={"weThink"}
            data-plasmic-override={overrides.weThink}
            className={classNames(projectcss.all, sty.weThink)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__s46ZZ)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__ikiLv)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__xQy75)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__tiOGo
                    )}
                  >
                    {"We think plants are the future"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jgVsS
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                      : "Word. But good code can  solve a lots of problems, too. New and old. That\u2019s why we help beginners get started with web development through free content and tools, like this theme. We also believe the JAMstack might be one solid pillar on which we build that future."}
                  </div>
                </Stack__>
                <div className={classNames(projectcss.all, sty.column__tmYui)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___2U11T)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "400px"
                        : "500px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "500px"
                        : "500px"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/planty/images/teamWebp.webp",
                      fullWidth: 1368,
                      fullHeight: 2048,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </Stack__>
            </div>
          </div>
          <Footer className={classNames("__wab_instance", sty.footer__etBuz)} />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "foreground2",
    "h1",
    "header",
    "featureItem",
    "bigPlants",
    "cactuses",
    "weLove",
    "weThink"
  ],
  foreground2: ["foreground2", "h1"],
  h1: ["h1"],
  header: ["header", "featureItem"],
  featureItem: ["featureItem"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"],
  weLove: ["weLove"],
  weThink: ["weThink"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  foreground2: "div";
  h1: "h1";
  header: "div";
  featureItem: typeof FeatureItem;
  bigPlants: "div";
  cactuses: "div";
  weLove: "div";
  weThink: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAboutUs__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAboutUs__VariantsArgs;
    args?: PlasmicAboutUs__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAboutUs__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAboutUs__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAboutUs__ArgProps,
          internalVariantPropNames: PlasmicAboutUs__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAboutUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAboutUs";
  } else {
    func.displayName = `PlasmicAboutUs.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutUs = Object.assign(
  // Top-level PlasmicAboutUs renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    foreground2: makeNodeComponent("foreground2"),
    h1: makeNodeComponent("h1"),
    header: makeNodeComponent("header"),
    featureItem: makeNodeComponent("featureItem"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    weLove: makeNodeComponent("weLove"),
    weThink: makeNodeComponent("weThink"),

    // Metadata about props expected for PlasmicAboutUs
    internalVariantProps: PlasmicAboutUs__VariantProps,
    internalArgProps: PlasmicAboutUs__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAboutUs;
/* prettier-ignore-end */
